/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.io.File;
import java.util.Iterator;
import java.util.Vector;
import Principal.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author rnlob
 */
public class TelaDeOutput extends javax.swing.JFrame {
    private Vector <Imovel> imoveis;
    Vector <Imovel> imoveisCriados = new Vector<Imovel>();
    File f;
    /**
     * Creates new form TelaDeOutput
     */
    //Passando algumas telas como invisíveis
    public TelaDeOutput() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanelCasa.setVisible(false);
    }
    //Trazendo algumas informações dos arquivos da outra tela
    public TelaDeOutput(Vector <Imovel> imoveis, File f) {
        this();
        this.imoveis = imoveis;
        this.f = f;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        valorImovel = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        nomeProprietario = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        nomeRua = new javax.swing.JTextField();
        nomeBairro = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        nomeCidade = new javax.swing.JTextField();
        numeroCasa = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        qtdQuartos = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        qtdBanheiros = new javax.swing.JTextField();
        jPanelCasa = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        especifico1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        especifico2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        especifico4 = new javax.swing.JTextField();
        especifico5 = new javax.swing.JTextField();
        especifico3 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Imobiliária");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Qual função deseja utilizar?");

        jComboBox1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1) Mostra todos os imóveis e suas características.", "2) Informe o nome para saber se esta pessoa possui imóveis.", "3) Informe um valor e mostraremos os imóveis com preço <=.", "4) Informe um valor e mostraremos imóveis que tem nº de quartos >=.", "5) Dite 1-casa 2-apartamento e 3 -chácara e mostraremos os imóveis ordenados.", "6) Informe uma cidade e mostraremos os imóveis em ordem decrescente.", "7) Informe o nome de um proprietário e mostraremos seus imóveis se possuir.", "8) Informe um vetor de imóveis e criaremos um arquivo com ele." }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Seu input:");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Output:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane1.setViewportView(jTextArea1);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Limpar tudo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Tipo de saída:");

        jLabel6.setText("Tipo de entrada:");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Arquivo txt");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Printar no output");

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("Escrever novo vetor");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jButton4.setText("Enviar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jRadioButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4)
                        .addComponent(jRadioButton4)))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jLabel7.setText("Label");

        jButton3.setText("Enviar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jButton3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setText("Tipo do imóvel:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casa", "Apartamento", "Chácara" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Valor:");

        jLabel10.setText("Proprietário:");

        jLabel11.setText("Rua:");

        jLabel12.setText("Bairro:");

        jLabel13.setText("Cidade:");

        jLabel14.setText("Número:");

        jLabel15.setText("Quartos:");

        jLabel16.setText("Banheiros:");

        jPanelCasa.setBackground(new java.awt.Color(153, 204, 255));

        jLabel20.setText("Específicas");

        jLabel21.setText("Label");

        jLabel22.setText("Label");

        jLabel17.setText("Label");

        jLabel18.setText("Label");

        jLabel19.setText("Label");

        javax.swing.GroupLayout jPanelCasaLayout = new javax.swing.GroupLayout(jPanelCasa);
        jPanelCasa.setLayout(jPanelCasaLayout);
        jPanelCasaLayout.setHorizontalGroup(
            jPanelCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCasaLayout.createSequentialGroup()
                .addGroup(jPanelCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCasaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)))
                    .addGroup(jPanelCasaLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel20))
                    .addGroup(jPanelCasaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21))
                        .addGap(42, 42, 42)
                        .addGroup(jPanelCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(especifico2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(especifico1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(especifico3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(especifico4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(especifico5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanelCasaLayout.setVerticalGroup(
            jPanelCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCasaLayout.createSequentialGroup()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(especifico1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(especifico2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(especifico3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(especifico4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(especifico5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton5.setText("Registrar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel15))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nomeRua, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(nomeProprietario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valorImovel, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(qtdQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qtdBanheiros, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numeroCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nomeCidade, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(nomeBairro))))
                .addGap(18, 18, 18)
                .addComponent(jPanelCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(valorImovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(nomeProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(nomeRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(numeroCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qtdBanheiros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(nomeBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(nomeCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(qtdQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanelCasa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 395, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(127, 127, 127)))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String itemSelected = jComboBox1.getSelectedItem() + "";
        if (itemSelected.equals("8) Informe um vetor de imóveis e criaremos um arquivo com ele.")) {
            jPanel1.setVisible(true);
        }
        else {
            jPanel1.setVisible(false);
            jPanel2.setVisible(false);
            jPanel3.setVisible(false);
        }
        
    }//GEN-LAST:event_jComboBox1ActionPerformed
    /*
    Esse trecho temos a escolha da função que a pessoa deseja fazer de acordo com as pré determinações
    do tp, onde podemos basicamente dar um.toString das funções ja definidas na classe Func, tendo isso
    em vista a tratativa de disposição do vetor de imoveis ficou no output localizado no canto direito 
    da tela
    */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (jComboBox1.getSelectedItem().toString().equals("1) Mostra todos os imóveis e suas características.")) {
            jTextArea1.setText(imoveis.toString());
        }
        else if (jComboBox1.getSelectedItem().toString().equals("2) Informe o nome para saber se esta pessoa possui imóveis.")) {
           if (Func.propriIdenti(imoveis, jTextField1.getText())){
                jTextArea1.setText("Possui");
            }
            else {
                jTextArea1.setText("Nao Possui");
            }
        }
        else if (jComboBox1.getSelectedItem().toString().equals("3) Informe um valor e mostraremos os imóveis com preço <=.")) {
            float valor;
            do{
                    
                valor = Float.parseFloat(jTextField1.getText());
                if(valor <= 0){
                    jTextArea1.setText("Valor deve ser positivo");
                }

            } while(valor <= 0);

            Vector <Imovel> auxValor = Func.valorBarato(imoveis, valor);

            if (auxValor.isEmpty()){
                jTextArea1.setText("Muito barato");
            }
            else {
                jTextArea1.setText(auxValor.toString());
            }
        }
        else if (jComboBox1.getSelectedItem().toString().equals("4) Informe um valor e mostraremos imóveis que tem nº de quartos >=.")) {
            int numeroDeQuartos = Integer.parseInt(jTextField1.getText());
            Vector <Imovel> auxQuarto = Func.muitosQuartos(imoveis, numeroDeQuartos);
            if (numeroDeQuartos < 0) {
                jTextArea1.setText("Valor invalido");
            }
            else {
                jTextArea1.setText(auxQuarto.toString());
            }
        }
        else if (jComboBox1.getSelectedItem().toString().equals("5) Dite 1-casa 2-apartamento e 3 -chácara e mostraremos os imóveis ordenados.")) {
            int imo = Integer.parseInt(jTextField1.getText());
            if(imo < 1 || imo > 3){
                jTextArea1.setText("Invalido");
            }
            Vector <Imovel> auxIm = Func.imovelUnico(imoveis, imo);
            int valor = auxIm.size();
            String todas[] = new String [valor] ;
            int i = 0;
            for (Imovel aux : auxIm) {
                if(aux instanceof Casa){
                    Casa temp = (Casa) aux;
                    String parte1 = String.format("%.2f", temp.getValor());
                    String parte2 = String.format("----- \n");
                    String parte3 = String.format("CASA\n");
                    String parte4 = String.format("Andares: %d\n", temp.getAndares());
                    String parte5 = String.format("Sala de Jantar: ");
                    String parte6;
                    if(temp.getSala_jantar()){
                        parte6 = String.format("SIM!!\n\n");
                    }
                    else{
                        parte6 = String.format("NÃO!!\n\n");
                    }
                    String total = parte1 + parte2 + parte3 + parte4 + parte5 + parte6;
                    todas[i] = total;
                }
                else if(aux instanceof Apartamento){

                    Apartamento temp = (Apartamento) aux;
                    String parte1 = String.format("%.2f", temp.getValor());
                    String parte2 = String.format("----- \n");
                    String parte3 = String.format("APARTAMENTO\n");
                    String parte4 = String.format("Andar: %d\n",  temp.getAndar());
                    String parte5 = String.format("Taxa de Condominio: %.2f\n",  temp.getTaxa_condominio());

                    String parte6 = String.format("Elevador: ");
                    String parte7;
                    if(temp.getElevador()){
                        parte7 = String.format("SIM!!\n");
                    }

                    else {
                        parte7 = String.format("NÃO!!\n");
                    }

                    String parte8 = String.format("Sacada: ");
                    String parte9;
                    if(temp.getSacada()){
                        parte9 = String.format("SIM!!\n\n");
                    }
                    else {
                        parte9 = String.format("NÃO!!\n\n");
                    }

                    String parte10 = String.format("----- \n");
                    String total = parte1 + parte2 + parte3 + parte4 + parte5 + parte6 + parte7 + parte8 + parte9 + parte10;
                    todas[i] = total;
                }
                else if(aux instanceof Chacara){

                    Chacara temp = (Chacara) aux;
                    String parte1 = String.format("%.2f", temp.getValor());
                    String parte2 = String.format("----- \n");
                    String parte3 = String.format("CHACARA\n");
                        
                    String parte4 = String.format("Salão de festa: ");
                    String parte5;
                    if(temp.getSalao_festa()){
                        parte5 = String.format("SIM!!\n");
                    }
                    else{
                        parte5 = String.format("NÃO!!\n");
                    }

                    String parte6 = String.format("Salão de jogos: ");
                    String parte7;
                    if(temp.getSalao_jogos()){
                        parte7 = String.format("SIM!!\n");
                    }
                    else{
                        parte7 = String.format("NÃO!!\n");
                    }

                    String parte8 = String.format("Campo de Futebol: ");
                    String parte9;
                    if(temp.getCampo_futebol()){
                        parte9 = String.format("SIM!!\n");
                    }

                    else{
                        parte9 = String.format("NÃO!!\n");
                    }

                    String parte10 = String.format("Churrasqueira: ");
                    String parte11;
                    if(temp.getChurrasqueira()){
                        parte11 = String.format("SIM!!\n");
                    }

                    else{
                        parte11 = String.format("NÃO!!\n");
                    }

                    String parte12 = String.format("Piscina: ");
                    String parte13;
                    if(temp.getPiscina()){
                        parte13 = String.format("SIM!!\n\n");
                    }
                    else{
                        parte13 = String.format("NÃO!!\n\n");
                    }

                    String parte14 = String.format("----- \n");
                    String total = parte1 + parte2 + parte3 + parte4 + parte5 + parte6 + parte7 + parte8 + parte9 + parte10 +  parte11 + parte12 + parte13 + parte14;
                    todas[i] = total;
                }
                i++;
            } 
            StringBuffer sb = new StringBuffer();
            for (String toda : todas) {
                sb.append(toda);
            }
            String str = sb.toString();
            jTextArea1.setText(str);
        }
        else if (jComboBox1.getSelectedItem().toString().equals("6) Informe uma cidade e mostraremos os imóveis em ordem decrescente.")) {
            Vector<Imovel> auxCity =  Func.cidadeImoveis(imoveis, jTextField1.getText());
            jTextArea1.setText(auxCity.toString());
        }
        else if (jComboBox1.getSelectedItem().toString().equals("7) Informe o nome de um proprietário e mostraremos seus imóveis se possuir.")) {
            Vector <Imovel> vetordeProp = Func.retornaPropries(imoveis, jTextField1.getText());
            int valor = vetordeProp.size();
            String todas[] = new String [valor] ;
            if (vetordeProp.isEmpty()){
                jTextArea1.setText("Sem imoveis");
            }
            else {
                Iterator <Imovel> iterador = vetordeProp.iterator();
                int i = 0;
                while (iterador.hasNext()){
                    todas[i] = String.format("%s", iterador.next());
                    i++;
                }
                StringBuffer sb = new StringBuffer();
                for (String toda : todas) {
                    sb.append(toda);
                }
                String str = sb.toString();
                jTextArea1.setText(str);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    //Botao que limpa os campos
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        desabilitaTudo();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed
    /*
    Esse botao ve se a pessoa habilitou os 2 RadioButton para ter certeza que ela quer criar
    um novo vetor e tambem quer salvar em txt ou mostrar no output
    */
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton4.isSelected()) {
            jLabel7.setText("Quantos imoveis irá registrar?");
            jPanel2.setVisible(true);
        }
    }//GEN-LAST:event_jButton4ActionPerformed
    //Pega o int para saber quantos registrar serao necessarios de acordo com a quantidade de imoveis
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int n = Integer.parseInt(jTextField2.getText());
        jPanel3.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed
    /*
    Aqui trata quis campos estaão habilitados de acordo com qual item da Panel de registro de imoveis
    foi selecionado, habilitando ou nao os campos neces~ários e colocando seus nomes das características
    específicas
    */
    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        String itemSelected = jComboBox2.getSelectedItem() + "";
        if (itemSelected.equals("Casa")) {
            jPanelCasa.setVisible(true);
            jLabel21.setText("Andares:");
            jLabel22.setText("Sala de jantar?");
            jLabel17.setVisible(false);
            jLabel18.setVisible(false);
            jLabel19.setVisible(false);
            especifico3.setVisible(false);
            especifico4.setVisible(false);
            especifico5.setVisible(false);
        }
        else if (itemSelected.equals("Apartamento")) {
            jPanelCasa.setVisible(true);
            jLabel21.setText("Andar:");
            jLabel22.setText("Taxa do condomínio:");
            jLabel17.setText("Elevador:");
            jLabel18.setText("Sacada:");
            jLabel17.setVisible(true);
            jLabel18.setVisible(true);
            jLabel19.setVisible(false);
            especifico3.setVisible(true);
            especifico4.setVisible(true);
            especifico5.setVisible(false);    
        }
        else if (itemSelected.equals("Chácara")) {
            jPanelCasa.setVisible(true);
            jLabel21.setText("Salao de festas?");
            jLabel22.setText("Salao de jogos?");
            jLabel17.setText("Campo de futebol?");
            jLabel18.setText("Churrasqueira?");
            jLabel19.setText("Piscina?");
            jLabel17.setVisible(true);
            jLabel18.setVisible(true);
            jLabel19.setVisible(true);
            especifico3.setVisible(true);
            especifico4.setVisible(true);
            especifico5.setVisible(true);
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed
    public void desabilitaTudo() {
        jTextField1.setText("");
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        jTextArea1.setText("");
        jPanelCasa.setVisible(false);
        jTextField2.setText("");
        valorImovel.setText("");
        nomeProprietario.setText("");
        nomeRua.setText("");
        nomeBairro.setText("");
        nomeCidade.setText("");
        numeroCasa.setText("");
        qtdQuartos.setText("");
        qtdBanheiros.setText("");
        especifico1.setText("");
        especifico2.setText("");
        especifico3.setText("");
        especifico4.setText("");
        especifico5.setText("");
        jComboBox2.setSelectedItem(null);
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        
        
    }
    /*
    Criação dos novos objetos de acordo com as informações preenchidas pelo usuário
    */
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
 
        if (jComboBox2.getSelectedItem().toString().equals("Casa")) { 
                    imoveisCriados.add(new Casa(1, Float.parseFloat(valorImovel.getText()),
                            nomeProprietario.getText(), nomeRua.getText(), nomeBairro.getText(),
                            nomeCidade.getText(), Integer.parseInt(numeroCasa.getText()),
                            Integer.parseInt(qtdQuartos.getText()),
                            Integer.parseInt(qtdBanheiros.getText()),
                            Integer.parseInt(especifico1.getText()),
                            Principal.Func.intToBoolean(especifico2.getText())));
        }
        
        else if (jComboBox2.getSelectedItem().toString().equals("Apartamento")) { 
                    imoveisCriados.add(new Apartamento(2, Float.parseFloat(valorImovel.getText()),
                            nomeProprietario.getText(), nomeRua.getText(), nomeBairro.getText(),
                            nomeCidade.getText(), Integer.parseInt(numeroCasa.getText()),
                            Integer.parseInt(qtdQuartos.getText()),
                            Integer.parseInt(qtdBanheiros.getText()),
                            Integer.parseInt(especifico1.getText()),
                            Float.parseFloat(especifico2.getText()),
                            Principal.Func.intToBoolean(especifico3.getText()),
                            Principal.Func.intToBoolean(especifico4.getText())));
        }
        
        else if (jComboBox2.getSelectedItem().toString().equals("Chácara")) { 
                    imoveisCriados.add(new Chacara(3, Float.parseFloat(valorImovel.getText()),
                            nomeProprietario.getText(), nomeRua.getText(), nomeBairro.getText(),
                            nomeCidade.getText(), Integer.parseInt(numeroCasa.getText()),
                            Integer.parseInt(qtdQuartos.getText()),
                            Integer.parseInt(qtdBanheiros.getText()),
                            Principal.Func.intToBoolean(especifico1.getText()),
                            Principal.Func.intToBoolean(especifico2.getText()),
                            Principal.Func.intToBoolean(especifico3.getText()),
                            Principal.Func.intToBoolean(especifico4.getText()),
                            Principal.Func.intToBoolean(especifico5.getText())));
        }
        //Aqui mostra no output o vetor criado
        if (imoveisCriados.size() == Integer.parseInt(jTextField2.getText())) {
            if(jRadioButton2.isSelected()) {
                jTextArea1.setText(imoveisCriados.toString());
            }
            /*
            Dispoe para o usuario a possibilidade de escolher o nome do arquivo e colocar no path
            que veio da outra tela
            */
            if(jRadioButton1.isSelected()) {
                String firstNameFile = JOptionPane.showInputDialog("Digite o nome do arquivo:");
                if (!firstNameFile.isEmpty()) {
                    desabilitaTudo();
                }
                Principal.Func.escreverTexto(String.format("%s\\%s.txt", f.getAbsolutePath(), firstNameFile), imoveisCriados);
            }
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeOutput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeOutput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeOutput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeOutput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeOutput().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JTextField especifico1;
    private javax.swing.JTextField especifico2;
    private javax.swing.JTextField especifico3;
    private javax.swing.JTextField especifico4;
    private javax.swing.JTextField especifico5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelCasa;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField nomeBairro;
    private javax.swing.JTextField nomeCidade;
    private javax.swing.JTextField nomeProprietario;
    private javax.swing.JTextField nomeRua;
    private javax.swing.JTextField numeroCasa;
    private javax.swing.JTextField qtdBanheiros;
    private javax.swing.JTextField qtdQuartos;
    private javax.swing.JTextField valorImovel;
    // End of variables declaration//GEN-END:variables
}
